#user:
#    resource: "@UserBundle/Controller/"
#    type:     annotation
#    prefix:   /

# charge tous les controllers dans le dossier précisé
#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

menu:
    resource: '@AppBundle/Controller/MenuController.php'
    type: annotation

request:
    resource: '@AppBundle/Controller/RequestController.php'
    type: annotation

twig:
    resource: '@AppBundle/Controller/TwigController.php'
    type: annotation

# importer une route à la fois
hello_the_world:
    path:     /hello-world
    defaults: { _controller: AppBundle:App:index }

salut:
    path:     /salut
    defaults: { _controller: AppBundle:App:salut }

bonjour:
    path:     /bonjour
    defaults: { _controller: AppBundle:App:bonjour }

aurevoir:
    path:     /aurevoir
    defaults: { _controller: AppBundle:App:aurevoir }

now:
    path:     /now
    defaults: { _controller: AppBundle:App:now }

routing:
    path:     /routing
    defaults: { _controller: AppBundle:App:routing }

#route avec des paramètres dynamiques
# on peut mettre une valeur par défaut à un paramètre d'url
routing_parameters:
    path:     /routing-parameters/user/{id}
    defaults: { _controller: AppBundle:App:routingParameters }

routing_parameters_test:
    path:     /routing-parameters-test/{test}
    defaults: { _controller: AppBundle:App:routingParametersTest, test: 'test' }
    # condition sur les paramètres : expression régulière pour
    # forcer un format de paramètre dynamique
    # si le format ne correspond pas, la route ne matche pas
    requirements: { test: \d+}
    methods:    [GET]

# on peut mettre des paramètres d'url n'importe dans le pattern de la route
routing_parameters2:
    path:     /routing-{param}parameters-{param2}test/{test}
    defaults: { _controller: AppBundle:App:routingParameters2 }