AppBundle\Entity\Article:
    type: entity
    table: ~
    repositoryClass: AppBundle\Repository\ArticleRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        createdAt:
            type: datetime
        enabled:
            type: boolean

    manyToOne:
        category:
            targetEntity: Category
            inversedBy: articles

    manyToMany:
        tags:
            targetEntity: AppBundle\Entity\Tag
            mappedBy: articles

    lifecycleCallbacks:
    # évenements déclenchés lors du cycle de vie d'une entité
    # nomEvenement: nomFonction
        prePersist: [prePersist]
        #postPersist: postPersist
        preUpdate: [preUpdate]
        #postUpdate: postUpdate
        #preRemove: preRemove
        #postRemove: postRemove
