AppBundle\Entity\Article:
    type: entity
    table: ~
    repositoryClass: AppBundle\Repository\ArticleRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        createdAt:
            type: datetime
        enabled:
            type: boolean

    lifecycleCallbacks: {  }
