AppBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        createdAt:
            type: datetime

    oneToMany:
        articles:
            targetEntity: AppBundle\Entity\Article
            mappedBy: category

    lifecycleCallbacks: {  }
